# Important areas for seabirds within NOMA {.unnumbered}

This section details seabird area use and its seasonal dynamics within each of the three Norwegian Ocean Management Areas (NOMA). The abundance models are able to resolve the year-round spatial density distribution of 97% of the seabird populations breeding across the Northeast Atlantic composed of the six pelagic seabird species within SEATRACK (Table 3). With these estimates we can make inferences about total abundances of seabirds present in each NOMA. 
It is apparent that numerically most seabirds are found within the Barents Sea NOMA year-round, followed by the Norwegian Sea. Least amount of birds are present in the North Sea. The most abundant species in each NOMA is the Atlantic puffin, while in the Barents Sea the Brünnich's guillemot is as abundant (Figure 9). Further, seabirds in each NOMA display distinct space use patterns. Most birds in the Barents Sea NOMA concentrate in the central southern part of this NOMA both in absolute (Figure 11) and relative terms (Figure 12) as well as in displayed species diversity (Figure 16). In contrast, both in the Norwegian Sea and North Sea NOMAs, most birds are found on the periphery of each respective area. The main concentration of birds in the Norwegian Sea NOMA can be found on the border to the Barents Sea and towards the Faroe Islands, while birds in the North Sea NOMA are mainly concentrated on the border closest to Scotland (Figure 11 and Figure 12). 

