# Overarching results {.unnumbered}

This chapter is structured into three sections dealing with (1) area use of North Atlantic seabirds within each Norwegian Ocean Management Area (NOMA) throughout the year, (2) area use across the North Atlantic throughout the year of seabirds breeding within each NOMA, and (3) migration corridors of seabirds breeding within each NOMA. The results presented utilize the **abundance dataset (f)** to make inferences about the *abundance* of the six most abundant seabird species within the SEATRACK dataset as well as the North Atlantic (black-legged kittiwake, Northern fulmar, little auk, Atlantic puffin, common guillemot, and Brünnich's guillemot). Additionally, species *diversity* has been estimated using the **diversity dataset (e)** based on the entire SEATRACK dataset of all elven species. Timing of breeding and migration in turn are based on the **breeding timing dataset (c)** (available for the 6 pelagic species and common eiders) and **migration timing dataset (h)** (available for the 6 pelagic species), respectively. Finally, migration corridors are assessed using the **migration routes intensity datasets (d)** (available for the 6 pelagic species).
