# Step 1 - Standardized field sampling and data collection {.unnumbered}

Through its established research network of xx partners from xx countries and its research infrastructure of xx colonies across the North Atlantic, the SEATRACK project has since 2014 deployed \>15 000 GLS loggers on 11 species of seabirds. Light‐level geolocators collect ambient light recordings that can be used to estimate the whereabouts of an individual over the time it carried the device. These data have to be downloaded from a device after a logger has been retrieved. Thus, data processing begins with a pre-processing phase that involves downloading and decompressing the raw data from the loggers as well as calibrating their internal clocks to adjust for potential time drift, crucial for the accurate estimation of geographic locations later on.

Equally important as the actual data collected by the GLS loggers is a comprehensive, comparable, and standardized field sampling protocol (Helgason et al., 2014-2023) and meta data catalogue detailing each logger deployment and retrieval. The field sampling protocol is updated annually and utilized by all project partners during their field work. It details the standardized procedure to deploy and retrieve devices, as well as recording the crucial meta data information.  These include ringing information (ringing date, ring number, euring code, color ring), logger information (logger status, logger model retrieved, logger id retrieved, logger model deployed, logger id deployed), information on individuals (species, morph, subspecies, age, sex, sexing method), morphometrics (weight, scull length, tarsus length, wing length), breeding status (breeding stage, number of eggs, number of chicks, hatching success, breeding success, breeding success criteria), breeding location (country, colony name, colony latitude, colony longitude, nest id), information on samples taken (blood, feather, others), as well as other relevant information (data responsible, bird came back to nest after capture, logger mount method, other relevant variables). To facilitate standardization many fields in the meta data form have been option coded while free fields such as date have clearly defined formats. The **meta and raw logger data (a)** include for each tracked individual: 1) meta data, 2) light level recordings, 3) wet/dry data, and 4) temperature readings, depending on logger model and species equipped.
